### ISSUE TITLE
What is the imported BLETracerPlugin 

### ISSUE THREAD

**Issue by Dealerpriest** [AndreasGassmann/WeTrace#14]
What is this plugin and why can't I find any documentation on it in the capacitor documentation?
https://github.com/AndreasGassmann/WeTrace/blob/e208d9fdd528a374728a7e52a29349a460679cde/src/app/services/device-proximity.service.ts#L5

**Comment by AndreasGassmann** [comment]
That's not an official capacitor plugin. It has been developed during the hackathon and is located in the native projects:

https://github.com/AndreasGassmann/WeTrace/blob/master/android/app/src/main/java/com/contacttracer/app/BLETracerPlugin.java
https://github.com/AndreasGassmann/WeTrace/blob/master/ios/App/App/BLETracerPlugin.m
